version: '3.7'

volumes:
    ocbr_database:

networks:
    ocbr_network:

services:
    ocbr:
        env_file:
            - .env
        container_name: opencartbrasil
        build:
          context: ./www
          dockerfile: Dockerfile
          args:
            VERSION: "1.x"
        ports:
            - ${HTTP_PORT}:80
        environment:
            - DB_HOSTNAME=ocbr_db
            - DB_USERNAME=${DB_USERNAME:?}
            - DB_PASSWORD=${DB_PASSWORD:?}
            - DB_DATABASE=opencartbrasil
            - USERNAME=${OPENCART_USER:?}
            - PASSWORD=${OPENCART_PASSWORD:?}
            - HTTP_SERVER=${URL:?}
        networks:
            - ocbr_network
        volumes:
            - ./www:/var/www/html
        depends_on:
            - ocbr_db

    ocbr_db:
        env_file:
            - .env
        image: mysql:5.7
        container_name: opencartbrasil_db
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?}
            - MYSQL_USER=${DB_USERNAME:?}
            - MYSQL_PASSWORD=${DB_PASSWORD:?}
            - MYSQL_DATABASE=${MYSQL_DATABASE:?}
            - MYSQL_TCP_PORT=${DB_PORT:?}
        ports:
            - ${DB_PORT}:3306
        expose:
            - 3306
        networks:
            - ocbr_network
        volumes:
            - ocbr_database:/var/lib/mysql